name: Veracode Dependency Scan
on:
  push:
    branches:
      - master
  pull_request:
    branches: ["master"]
  schedule:
    - cron: '26 3 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: Run Veracode Dependency Scan
      uses: veracode/veracode-sca@v2.1.6
      with:
        veracode_api_id: ${{ secrets.VERACODE_API_ID }}
        veracode_api_key: ${{ secrets.VERACODE_API_KEY }}
        fail_on_cvss: 9.0
