name: Veracode Dependency Scan
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Run Veracode Dependency Scan
      uses: veracode/dependency-check-action@v1.3
      with:
        veracode_api_id: ${{ secrets.VERACODE_API_ID }}
        veracode_api_key: ${{ secrets.VERACODE_API_KEY }}
        fail_on_cvss: 9.0
