name: Veracode Dependency Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
  schedule:
    - cron: '26 3 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install Veracode Dependency Check CLI
        run: |
          curl -sSL -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v8.1.2/dependency-check-8.1.2-release.zip
          unzip dependency-check.zip
      - name: Run Veracode Dependency Scan
        run: ./dependency-check/bin/dependency-check.sh --project "My Project" --scan .
